import json
crit=[]
def c(cat,sev,d,a): crit.append(dict(category=cat,severity=sev,description=d,suggested_action=a))

c("evidence","major",
"A fifth iteration-4 artifact ran, was abandoned, and is missing from the record: iter_4/gen_art/gen_art_experiment_13 ('held-out C-LAG confirmation + RQ2 under a newly selected Heretic edit'). It was strategy slot 2 (gen_strat_1/README.md), the one slot aimed at the previous review's top coverage debt: the frozen-core edit and natural RefusEU FINAL pairs with ASR. The report's iter-4 Strategy lists only three problems and 'four artifacts' and never mentions it. What the workspace shows:\n(i) protocol.yaml AMENDMENT_A1_GPU_LOST: the L4 GPU was revoked ~25 min in, so the new Heretic edit, DEV grid, the B-300 confirmation curve, random controls and RQ2 natural pairs were NOT executed.\n(ii) An executed tier bake-off, results/tier_table.json: on eval2's 240 adjudicated edited rows, gemini-2.5-flash had Sp 0.42-0.55 per cell (overall kappa 0.47) and flash-lite had Sp 0.27-0.36. Both failed the gate (amendment A3). This is a second, independent measurement that the paid primary judge over-calls REFUSE on edited rows, and it is worse than eval3's Sp 0.66-0.73.\n(iii) A substitute paid re-readout of E9/E11 was frozen (commit 065fbb45; 19,195 rows in results/final/readout_rows.jsonl). No labels were written (results/labels empty) because of the key limit (A4; logs/judge_all.log loops on 'platform key limit').\n(iv) A frozen 519-item external pool with a DEV/B/C split (data/split_manifest_iter4.json).",
"Add an 'Artifact 19 (not executed): exp13' subsection to Iteration 4 with the GPU-loss amendment, the tier_table.json per-cell Se/Sp/kappa table for both tiers, the frozen-but-unlabelled re-readout design, and the preserved item pool. Add it to the iter-4 dead-ends table. Change the Strategy to say that five slots were planned and slot 2 (frozen-core edit + RQ2) failed. Carry the RQ2/frozen-core debt forward explicitly.")

c("evidence","major",
"The experiment-14 tables do not match the artifact (results/RESULTS_tables.md, generated from analysis.json).\nTable 28 (Gemma, high dose) against the artifact:\n- EN->HU: 0.62 reported, 0.46 in the artifact.\n- SL row: 0.25/0.81/0.68 reported, 0.07/0.56/0.53 in the artifact.\n- HU row: 0.22/0.75/0.64 reported, 0.10/0.83/0.55 in the artifact.\nOnly EN->EN 0.18 and EN->SL 0.77 are correct.\nTable 29 (GaMS, high dose): EN->HU 0.18 vs 0.23, SL->EN 0.19 vs 0.16, HU->SL 0.15 vs 0.12, HU->HU 0.19 vs 0.28. 'Largest cell difference 0.07' is really 0.16.\nTable 30, GaMS row: OUT_SL +0.05 [-0.35,0.42] and IN_SL -0.12 [-0.51,0.28] are reported. The artifact gives -0.44 [-0.98,0.27] and -0.86 [-1.58,-0.13]; GaMS's IN_SL CI excludes 0.\nProse errors:\n- 'SL input adds about 0.04-0.07': Gemma IN_SL is -0.60 [-1.02,-0.18]. A Slovene input LOWERS refusal (SL->EN 0.07 vs EN->EN 0.18; SL->SL 0.56 vs EN->SL 0.77).\n- 'EN-output refusal 0.18-0.25 across input languages': the actual range is 0.07-0.18.\n- SDT 'DiD in d' was -0.42 [-0.89,0.12]': the artifact gives hi|SLoutput d' DiD +0.72 [-0.06,1.30].\nNone of the misreported values appears anywhere in the artifact, so they are untraceable numbers presented as results.",
"Regenerate Tables 28-30 and the exp14 prose directly from results/RESULTS_tables.md. Include all three doses (zero/lo/hi), the pew_heretic row, the per-cell language-compliance column, and the full mechanism-contrast table for every readout (raw_R, rg_R, ppi_R; ttj_R and second_R are NA). Add the 'Edit-induced lag L*' table (G3 and G3_edit per cell) and the full SDT DiD list. Add a correction marker that states what was wrong.")

c("rigor","major",
"The iteration's central conclusion ('The lag is not edit-induced. The edit-induced component spans zero in every item body under every readout ... pre-edit baseline gap is negative everywhere') is contradicted by the run's own tables.\nG3_edit excludes zero in the NEGATIVE direction in three places:\n- exp14's pre-registered G3_edit for SL->SL is -1.84 [-2.80,-0.78], model-swap p=0.000 (EN->SL -1.26, HU->SL -2.15 [-3.16,-0.46]).\n- eval3's own exp10 op-point row gives G3_edit -3.40 [-6.09,-1.30].\n- eval3's exp8_B lexicon row gives -1.72 [-3.69,-0.52].\nIt excludes zero in the POSITIVE direction elsewhere: exp9 raw +1.43 [0.29,2.98], archived J1 +2.23, and q14 exp8 +3.21/+3.59.\nG3_orig CIs include 0 in exp8_A1 [-2.67,0.04], exp8_B [-2.37,0.78] and exp15 [-2.83,0.22]; at the exp10 op point it is +0.99.\nI recomputed exp15's G3_orig from the per-step table with the Hautus correction: Gemma margin 1.483 (SL 299/300 vs EN 294/300), GaMS 0.313, G3_orig -1.17. It rests on Gemma having 1 vs 6 non-refusals out of 300 at ceiling. If Gemma SL were 296/300 (3 items), G3_orig would be -0.06.\nThe exp15 text also misuses the MDE. 0.42 is the MDE of G3, not of G3_edit. The artifact's own 90% bound is |G3_edit| < 1.91, and the pooled G3_edit CI [-1.95,2.74] contains -m. An edit-induced lag of the pre-registered size is therefore not excluded.\nThe b slopes are also not 'both near 1': eval3 b_Gemma is 1.40-1.66 and b_GaMS 0.97-1.13, and exp9's CIs do not overlap.",
"Downgrade R-BASE to 'not refuted; decomposition of G3 into baseline and edit components is underdetermined'. Tabulate G3_orig and G3_edit for every body and readout, including exp14 SL->SL and the exp10 op point. Report a ceiling-sensitivity analysis of G3_orig (leave-k-items, and a Jeffreys or exact alternative to Hautus). Delete the '0.42 MDE' sentence about G3_edit and quote the 90% bound 1.91. Replace 'curves are parallel' with the slope CIs.")

c("evidence","major",
"The report says 'The lag sign is robust; its magnitude is not'. eval3's own tipping table (READOUT_v2.md) says the opposite. For G3 'to_zero' in both exp9_lambda (delta* 0.545, eps* 0.13) and exp11_final (delta* 0.46, eps* 0.205), the measured error CIs reach BOTH thresholds. The artifact concludes 'judge error alone can still account for the lag'.\nThe report's sentence 'Gemma-SL 1-Sp (0.34) exceeds the delta* ... exp9 (0.36)' is also arithmetically false: 0.34 < 0.36; only the CI reaches it.\n'Negative sign under every readout, every judge' is also contradicted in the per-curve table:\n- gpt-4.1-mini second family, exp9: +1.27 [-3.23,3.01]\n- archived Qwen3-14B, exp8_A1: +1.57 [0.11,3.00] (positive, CI excludes 0)\n- archived Qwen3-14B, exp8_B: +1.57\n- Mistral-24B: +7.58 and +0.04\n- exp9 B' J1: +9.33\nThe pooled TTJ G3 CI [-4.67,2.47] also includes 0.",
"Rewrite the eval3 Outcome and the C-LAG paragraph of 'What we have learned so far': 'sign not robust to the measured judge error (both tipping paths reach zero in exp9 and exp11); sign negative under gemini raw, PPI and J1-TTJ, but positive under the gpt-4.1-mini second family and archived Qwen3-14B on some bodies'. Copy eval3's full per-curve table (all readouts) and the tipping table verbatim.")

c("methodology","major",
"exp14's GaMS arm failed its manipulation, and the report misstates this. The output-language suffix is the manipulation M-OUT/M-IN rests on. analysis.json compliance_gate gives GaMS compliance of 0.00 for SL->EN, 0.14 for HU->EN, 0.555 for SL->HU and 0.865 for HU->SL. GaMS answers a Slovene prompt in Slovene even when told to answer in English. The report says compliance was '>90% in all cells except HU output for GaMS3 at high dose (87%)'.\nThe GaMS OUT/IN contrasts, and therefore the cross-model dOUT_SL = -1.58 and dIN_SL, compare a model that follows the instruction with one that does not.\nOther departures the report leaves out:\n- The GaMS dose bracket failed (straddle False, support_ok False).\n- The primary readout was the local J1 classifier after the key limit (A4), not a paid judge.\n- The phase-4 gate failed; kappa against gpt-4.1-mini is empty, and the TTJ/second readouts are NA.\n- Under RG and PPI, P0 fails ('no lag to decompose'), and robust_call_SL is False.\n- MT noise at lambda 0 is significant (EN-orig vs EN-BT McNemar p=0.019 Gemma, 0.005 GaMS).\n- C-EXT was cut to one checkpoint (A3).",
"Correct the compliance sentence using the compliance_gate table. State that the cross-model M-OUT contrast is invalid wherever GaMS failed compliance. Restrict M-OUT to 'Gemma-only, raw J1 readout plus 120-row author-model gold (0.50 vs 0.33; non-EN-input/EN-output 0.38, n=21), not robust by the pre-registered 4-readout rule'. List the A3/A4/A5 amendments, the support failure and the MT-noise result.")

c("clarity","major",
"The iteration-4 framing misstates the judge situation. The Strategy says 'The OpenRouter shared key was available for this iteration. All paid judge calls used gemini-2.5-flash and gpt-4.1-mini.' Every executing artifact hit the key limit:\n- eval3 AM2: ASR stopped at 1,108/5,800 and R-INCAP was not executed; the TTJ arm was judged by exp9's local J1, not a paid judge; 195 of 480 adjudication rows were labelled by the executing agent.\n- exp13 A4: no labels were written.\n- exp14 A4: J1 became primary.\n- exp15: the $12 limit forced the J1 fallback, and gpt-4.1-mini labels exist for Gemma cells only (GaMS 'NA').\nThe eval3 section describes TTJ as translate-then-judge without saying which judge, and it omits eval3's correction C1: the 590-row 'gold calibration' block holds prompt hazard-category gold, not refusal labels.",
"Rewrite the iter-4 Strategy paragraph and each artifact's judge line to say which readout is local J1 and which is paid. Add AM2 and C1 to the eval3 section. Report the partial ASR result from the 1,108 rows or state that it is unused.")

c("evidence","major",
"Iteration-4 SDT evidence overturns the report's restricted criterion-shift claim, and that evidence is left out. 'What we have learned so far' says the criterion difference 'disappears on edited models' and is 'specific to the original-model hard-prompt setting'. But:\n- exp15 analysis.json sdt/R gives DiD_c_ref_window = -0.33 and DiD_c_ref_lam0 = -0.39 on RefusEU harmful items with benign twins, against DiD_d' of -0.18 and -0.06. The artifact summary says 'SDT shows a criterion component', so R-JUDGE 'only partly holds'.\n- exp14 gives hi|SLoutput DiD_c = -1.56 [-1.97,-1.29], zero|SLoutput -0.76 [-1.06,-0.52], and zero|SLboth -0.47.\nOn edited models and on non-HARD items, the model difference is in c after all. The exp15 per-step SDT table is also summarised, not reproduced.",
"Add exp15's SDT DiD values (window and lambda-0, d' and c) and exp14's six SDT DiD lines. Rewrite the criterion-shift claim so it reflects iter-3 (exp9 DiD_c ~0) and iter-4 (exp15 and exp14 DiD_c non-zero) disagreeing, with item bodies and judges named.")

c("evidence","major",
"Several MUST-FIX items from the previous review were addressed only with correction boxes. The requested tables are still missing, and uncorrected body text now contradicts the boxes.\n- exp11: no per-step Hautus table, no per-model a/b table, no four-readout G3 table (q_R, q_RP, incl_orig, excl_chrF50), no Qwen/Mistral gate tables, and no 5-cell adjudication table (Gemma SL Sp 0.22 is still absent). The 'Why the test was underpowered' paragraph still gives the one-sided 'judge over-calls English' story and the wrong 'specificity 0.33 (kappa 0.27)'.\n- exp9: no SDT subsection. The heading 'Lambda curve: lag confirmed' stands.\n- exp10: no geometry, induction or add-on tables. 'Final verdict: Both ... REFUTED' stands under a box that says M-a is layer-dependent. 'GaMS English censored' is still in the induction body.\n- exp12: no Belebele table. The first-token KL EN/SL columns of Table 24 are dashes.\n- The 'learned' paragraph lacks eval2's RG-corrected -5.10 [-11.17,5.60] and q14 +1.57.\n- Table 9 still shows C3 = -1.76 [-2.73,-1.09].",
"Copy the requested tables from exp11 results/RESULTS_tables.md, exp9 analysis.json['SDT'], exp10 summary_tables.md and exp12 RESULTS.md into the report. Wherever a correction box contradicts a heading or verdict sentence, add an inline strike or '[superseded, see box]' marker. Add the eval2 values to the C-LAG paragraph. Fix Table 9.")

c("scope","major",
"Coverage of the original request is still partial, and iteration 4 made no progress on the frozen-core debt because exp13 died unrecorded.\n- RQ2 is not done: no natural RefusEU FINAL EN/SL pairs were scored under the edit, and no RefusEU-protocol ASR is reported.\n- The research artifact (art_NZ9n2Ej5RtGt) established that Heretic @3521f86 has NO automatic selection rule and defaults to 200 trials / 60 startup. The report nevertheless repeats 'frozen-core Heretic procedure (bf16, 80 trials, Heretic's own selection rule) has never been run' as an open item and keeps it unchanged in the coverage table.\n- Two artifacts wrote formal native-speaker audit requests (exp14 results/human_audit_request.json; eval3). The report does not list them as a human-input item.\n- The user asked that every headline be traceable and that the conclusions reconcile with the strongest surviving evidence. The exp14 mismatches and the R-BASE overstatement fail that request.",
"Update the coverage table: RQ2 NOT DONE (exp13 GPU loss); frozen core respecified per the research artifact (pre-registered KL<=0.5 selection rule, 200/60 defaults, NF4 deviation). List the human-audit request as a human-input item with its spec. For the final iteration, put the budget on RQ2 natural pairs + ASR, plus a larger adjudicated edited-row set. Add no further mechanism probes.")

c("novelty","minor",
"The novelty and proportionality statements for the two iteration-4 positive claims need tightening.\n(a) M-OUT: 'no prior study separates input from output language; this design is novel' is stated flatly. The research artifact rates its own confidence as MEDIUM and notes that its unchecked-lane base rate was 11/11 occupied. The effect is Gemma-only (GaMS failed compliance) and depends on an output-language instruction suffix. Nearest neighbours: Shen et al. 2024 (low-resource output quality drives unsafe/irrelevant responses), Deng et al. 2023 (instruction language) and Upadhyaya & Sikdar 2026.\n(b) If R-BASE holds, the four-iteration C-LAG line reduces to the pre-edit GaMS Slovene deficit already measured in iterations 1-2 (DiD -0.35 to -0.67; meta -0.50). That is an expected-direction result, and it should be said plainly.",
"Qualify the M-OUT novelty as 'medium confidence, Gemma-only, instruction-suffix design'. State the delta over Shen et al. and Upadhyaya & Sikdar. Add one sentence tying R-BASE back to the iteration-1/2 DiD estimates.")

c("clarity","minor",
"Untraceable or misattributed numbers in the iteration-4 sections:\n- exp15 'pooled edited kappa is 0.51': not in exp15 RESULTS.md; it is exp14's number.\n- 'the best validation numbers in the study': exp14 GaMS SL edited Sp is 0.81, higher.\n- The exp14 BPB figures 'Gemma SL 1.20 vs GaMS3 0.89' come from exp12 results/competence_covariates.json, which is not cited.\n- 'u_lang alpha50 ... 2.96 in GaMS3' in 'learned' is the ENGLISH alpha50; the Slovene value is 1.78.\n- The iter-3 dead-ends table cites 'exp13 RESULTS_tables.md' for C-EXT. That file does not exist; it is exp11's.\n- exp15 has 14 Gemma and 15 GaMS steps including lambda 0. The item scale was cut from the strategy's 400+200 to 300+120, and that is not recorded.\n- The claim that the excess SL KL ratio is below 1 'across all iterations' is not computed for exp15. I recomputed it from exp15's KL table at the top dose: about 0.96 for Gemma and 0.80 for GaMS. Raw Gemma first-token KL is higher in Slovene (0.74 vs 0.38).",
"Fix each attribution. Compute and report the exp15 excess KL ratio with a CI. Record the exp15 scale reduction and its reason.")

c("clarity","minor",
"Iteration 4 records no hypothesis-update reasoning and has no end-of-iteration verdict table. The Strategy attributes the M-OUT/M-IN reframing to 'the iter-2 hypothesis update', but the M-OUT/M-IN framing appears to come from the iter-3 update. The pre-registered iter-4 outcomes of each artifact are never put in one table:\n- eval3: READOUT NOT VALIDATED / REFUTE-BOUND\n- exp14: raw M-OUT, robust False\n- exp15: ESTIMATE, LAG_SCREEN_SUPPORTED False, R_BASE_SUPPORTED True\n- exp13: not executed",
"Add a 'Why iteration 4 looked like this' paragraph quoting the iter-3 hypothesis update and the previous review's directives. End the iteration with a verdict table covering every pre-registered claim and rival (C-LAG, R-BASE, R-JUDGE, R-INCAP, M-OUT, M-IN, C-EXT, RQ2).")

out=dict(
overall_assessment="The iteration-4 record is not ready to ship, for three reasons.\n\nFirst, it omits an executed-then-abandoned artifact. exp13 (the frozen-core/RQ2 confirmation) lost its GPU, but its paid-judge tier bake-off still ran and failed (gemini-2.5-flash Sp 0.42-0.55).\n\nSecond, it reports exp14 tables whose values do not match the artifact. Most of Table 28, Table 29 and the GaMS row of Table 30 cannot be found in results/RESULTS_tables.md, and the output-language compliance failure in GaMS is misstated.\n\nThird, it states conclusions that contradict its own tables:\n- 'Lag not edit-induced; G3_edit spans zero in every body under every readout': exp14's pre-registered SL->SL G3_edit = -1.84 [-2.80,-0.78] and eval3's exp10 op-point G3_edit = -3.40 [-6.09,-1.30] exclude zero.\n- 'Sign robust': eval3's tipping table reaches zero on both paths.\n- 'Negative under every judge': the gpt-4.1-mini and Qwen3-14B rows are positive.\n- 'Criterion shift disappears on edited models': exp15 DiD_c -0.33 and exp14 DiD_c -1.56 say otherwise.\n\nI recomputed from the files:\n- exp15's headline G3/G3_orig/G3_edit and per-step margins match (G3_orig -1.17 reproduced exactly with Hautus). But G3_orig hinges on Gemma having 1 vs 6 non-refusals out of 300 at ceiling; three items erase it.\n- eval3's pooled table (-1.17 / +0.39) matches READOUT_v2.md.\n- The exp14 numbers above do not match.\n\nThe iter-1 to iter-3 corrections from the previous review were added as in-place boxes, which preserves the chronology. But many of the requested tables (exp11, exp9 SDT, exp10, exp12 Belebele) are still missing, and several superseded headings still stand. results_reported is false because headline exp14 numbers are untraceable. Soundness is 1 because headline conclusions contradict the run's evidence. The review is therefore blocking.",
strengths=[
"The iter-1 to iter-3 corrections requested by the previous review are inserted in place as dated, numbered boxes rather than as silent rewrites, so the chronology is preserved. A dead-ends table, a coverage-against-frozen-core table and a budget-misallocation note were added.",
"eval3's headline tables (gate Se/Sp, pooled REML+HKSJ G3 / G3_edit / IG across readouts, R-JUDGE comparisons) are copied accurately; I matched them to READOUT_v2.md.",
"exp15's headline decomposition (G3 -0.70 [-1.01,-0.42], G3_orig -1.17, G3_edit +0.47, the RG/PPI/TTJ rows, the MT-noise and random-control tables) matches RESULTS.md. I reproduced G3_orig from the per-step counts.",
"The report now says plainly that the readout gate has never passed, that all adjudication is by the author model rather than a human, and that no artifact's pre-registered verdict is CONFIRM.",
"Nearest-neighbour comparisons (Wang 2025, Aziz 2026, Upadhyaya & Sikdar 2026, Balani & Panda) are now given for the earlier positive claims, and RQ4 is correctly relabelled as a replication/source-separability result."],
dimension_scores=[
dict(dimension="soundness",score=1,justification="Headline iteration-4 conclusions contradict the run's own tables. The 'not edit-induced' claim is contradicted by exp14 SL->SL G3_edit -1.84 and eval3 exp10 G3_edit -3.40. 'Sign robust' is contradicted by eval3's tipping to zero. 'Negative under every judge' is contradicted by the positive gpt-4.1-mini and Qwen3-14B rows. The criterion-shift claim is contradicted by the exp15 and exp14 DiD_c values. The exp14 tables are untraceable.",
 improvements=["Regenerate the exp14 tables and prose from results/RESULTS_tables.md; this restores traceability and removes the fabricated-looking values.","Restate R-BASE as 'not refuted, decomposition underdetermined', with the G3_orig ceiling sensitivity and the 90% G3_edit bound of 1.91.","Rewrite the sign-robustness and 'every readout' sentences to match eval3's tipping and per-curve tables.","Restrict M-OUT to Gemma and record the GaMS compliance failure."]),
dict(dimension="presentation",score=2,justification="Correction boxes are clear, but the body text they supersede still stands in several places: 'lag confirmed', 'both REFUTED', 'censored'. The iter-4 Strategy misstates the judge situation, and there is no iteration-4 verdict table.",
 improvements=["Mark superseded headings and verdict sentences inline.","Add a 'Why iteration 4 looked like this' paragraph and an end-of-iteration verdict table.","Name the actual judge (paid vs local J1) on every iter-4 number."]),
dict(dimension="contribution",score=2,justification="The record omits the whole exp13 artifact (abandoned, but its tier bake-off executed), the exp14 G3/G3_edit per-cell table, the SDT DiD values, and the compliance table. It also still lacks many tables requested last round (exp11 per-step/a-b/four-readout/gates/adjudication, exp9 SDT, exp10 tables, exp12 Belebele).",
 improvements=["Add an exp13 subsection with tier_table.json and its amendments.","Copy the missing exp11, exp9, exp10 and exp12 tables.","Add eval3's full per-curve and tipping tables and exp15's SDT DiD values."])],
critiques=crit,
results_reported=False,
coverage="partial",
blocking=True,
score=3,
confidence=4)
json.dump(out,open('.terminal_claude_agent_struct_out.json','w'),indent=1,ensure_ascii=False)
print(len(crit))
